name: 'poc'
version: '0.1'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  acxiom:
    materialized: table
    #enabled: false


  vars:
    "base.test": "acxiom_test.test"
